### ISSUE TITLE
The Roadmap

### ISSUE THREAD

**Issue by CraigglesO** [Open-S2/s2maps-gpu#2]
Large scale progress tracker

# Beta Phase

### Sub Packages

- [x] React
- [x] Vue
- [ ] Svelte

### Render Mechanics

- [x] WebGPU Glyph-icon pairs not working
- [ ] WebGPU cursor interactivity for `Fills` not working as intended
- [x] WebGPU cursor interactivity for `Glyphs` not working as intended
- [x] Glyphs text-along-path
- [x] WM Projection -> allow option to force minzoom to be limited to show whole map on canvas at a minimum
- [x] WM Projection -> duplicate on the x axis
- [x] Hash -> URL synced with map position
- [x] Tile flush working across workers to know when tiles are fully rendered
    - [x] Source (used by most)
    - [x] Marker source
    - [x] Local source
- [x] awaitFullyRendered
- [x] screenshot

### Stability

- [x] Zooming is smoother for WebGPU and tiles visually stay while zooming out.
- [ ] Dashed lines is bugged
- [ ] glyphs along path don't coexist with other glyphs yet.
- [x] WebGPU sometimes tries to render deleted tiles. Rare case and doesn't seem to inhibit user interaction?
- [x] tile duplicates on the x axis -> parent tiles don't show
- [x] Glyphs overlap as you zoom in (not killing parent glyphs correctly?)
- [x] Some WebGPU Workflows can be converted to async from the painter
- [x] Migrate the WebGL "Programs" to work the same way as "Workflows" from WebGPU
- [x] Get unicode/LTR/substitution Zig parser out of experimental to production ready
- [x] `offscreen: false` is blurrier than offscreen.
- [x] changing screen size doesn't update view if needed

### Testing

- [x] All examples have WebGL1, WebGL2, and WebGPU tests to ensure they work before any more code is added.
    - [x] All text/icon type tests
    - [x] dashed lines

---

### NOTE:
Upon completion of Beta, and before beginning work on a 1.0 release, there will be a waiting period to see if any major changes are required before deciding upon a complete product.

---

# 1.0 RELEASE

### Features

- [ ] zoom out keeps children tiles
- [ ] Comments for all code
- [ ] raster fade-in from parent
- [x] snapshot post flush
- [ ] improve zooming in webgl1 for fill just like heatmap
- [ ] webgl1 sorting fallback last doesnt work
- [ ] Style/MapOptions converter for Mapbox
- [ ] Style/MapOptions converter for Maplibre
- [ ] S2 Clustering
- [ ] Hillshade works correctly for 512x512 images
- [x] Unicode parsing via Zig module Completed
- [ ] Glyphs Alpha fading
- [ ] move mouse position over canvas and get visual changes
- [ ] Fill pattern -> support scaling the image

### API

- [ ] getBounds/setBounds
- [ ] getMaxBounds/setMaxBounds
- [ ] setProjection/getProjection
- [ ] addSource/deleteSource
- [ ] addLayer/deleteLayer/updateLayer
- [ ] getStyle
- [ ] getFeatureState/DeleteFeatureState/setFeatureState

### Build

- [ ] Support a single file build that can use offscreen canvas `new Worker(new URL(..., import.meta.url), { ... })`
- [ ] NodeJS/Bun local builds for webgpu
- [ ] A foundation for native.

### Stability
- [ ] TODO - fill this section correctly
- [ ] Webgpu Glyph filtering doesn't properly follow a robust ordered pattern like webgl does
- [ ] Testing pipeline via actions (after release for free github actions, but first to fix)
- [ ] zooming towards cursor is a bit off for both cases.

### Testing (Excluding WebGL / WebGPU)

- [ ] Server side rendering WebGPU tests
  - [ ] mouse interactions
  - [ ] zoom interactions
  - [ ] hover value
  - [ ] popup on hover
- [ ] Plugins tests
- [ ] UI
    - [ ] projector
        - [ ] getTiles
        - [ ] cursorToLonLat
        - [ ] mat4
     - [ ] animator
     - [ ] cache
     - [ ] dragPan
     - [ ] timeCache
- [ ] Workers
     - [ ] process
        - [ ] glyph
        - [ ] util
        - [ ] fill
        - [ ] line
        - [ ] point
        - [ ] raster
     - [ ] source
        - [ ] json-vt
        - [ ] point-cluster / ClusterSource
        - [ ] glyphSource
        - [ ] imageSource
        - [ ] jsonSource
        - [ ] localSource
        - [ ] markerSource
        - [ ] s2tilesSource
        - [ ] spriteSource
        - [ ] texturePack

### Documentation
- [x] TODO - fill this section correctly
